apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditcard-worker
  namespace: e-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: creditcard-worker
  template:
    metadata:
      labels:
        app: creditcard-worker
    spec:
      containers:
        - name: creditcard-worker
          image: docker.io/rizkyian78/e-ticketing-creditcard-worker:e67f0c6
          imagePullPolicy: Always
          env:
           - name: AMQP_URL
             value: amqp://guest:guest@rabbitmq.e-ticket.svc.cluster.local:5672/
           - name: DATABASE_URL
             value: postgresql://postgres:password@postgres.e-ticket.svc.cluster.local:5432/ipg?sslmode=disable

