apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-app
  namespace: e-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice-app
  template:
    metadata:
      labels:
        app: backoffice-app
    spec:
      containers:
        - name: backoffice-app
          image: docker.io/rizkyian78/e-ticketing-backoffice-app:2fba526
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
