apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoshop
  namespace: e-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoshop
  template:
    metadata:
      labels:
        app: demoshop
    spec:
      containers:
        - name: demoshop
          image: docker.io/rizkyian78/e-ticketing-demoshop:fe224a0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_TICKET_SERVICE_URL
              value: "https://rizkyiann8nautomation.my.id/api/tickets"
            - name: VITE_API_PAYMENT_SERVICE_URL
              value: "https://rizkyiann8nautomation.my.id/api"
            - name: VITE_API_KEY
              value: "sk_live_9f8a7b6c5d4e3f2a1"

