apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-app
  namespace: e-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-app
  template:
    metadata:
      labels:
        app: checkout-app
    spec:
      containers:
        - name: checkout-app
          image: docker.io/rizkyian78/e-ticketing-checkout-app:e67f0c6
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
