apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  namespace: e-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      containers:
        - name: ledger-service
          image: docker.io/rizkyian78/e-ticketing-ledger:28247a4
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: ipg
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: password
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets

