apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: e-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: docker.io/rizkyian78/e-ticketing-payment:f6e1e2d
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq.e-ticket.svc.cluster.local
            - name: RABBITMQ_USER
              value: guest
            - name: RABBITMQ_PASS
              value: guest
            - name: DATABASE_URL
              value: postgresql://postgres:password@postgres.e-ticket.svc.cluster.local:5432/ipg
            - name: LEDGER_SERVICE_URL
              value: http://ledger-service.e-ticket.svc.cluster.local:3000
            - name: CHECKOUT_BASE_URL
              value: "https://checkoutpage.site/"
