apiVersion: apps/v1
kind: Deployment
metadata:
  name: qris-worker
  namespace: e-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qris-worker
  template:
    metadata:
      labels:
        app: qris-worker
    spec:  # remove if image is public
      containers:
        - name: qris-worker
          image: docker.io/rizkyian78/e-ticketing-qris-worker:484acc8
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: WORKER_TYPE
              value: "qris"
            - name: AMQP_URL
              value: amqp://guest:guest@rabbitmq.e-ticket.svc.cluster.local:5672/
            - name: DATABASE_URL
              value: postgresql://postgres:password@postgres.e-ticket.svc.cluster.local:5432/worker?sslmode=disable
