apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  namespace: e-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: rizkyian78/e-ticketing-ticket:6048c18
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres;Port=5432;Database=ipg;Username=postgres;Password=password"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets

