apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-app
  namespace: e-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backoffice-app
  template:
    metadata:
      labels:
        app: backoffice-app
    spec:
      containers:
        - name: backoffice-app
          image: rizkyian78/e-ticketing-backoffice-app:10ced76ff2daf0e3c252cf88844e341bd109fb4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
