apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: e-ticket
  namespace: argocd
spec:
  description: E-Ticketing platform

  sourceRepos:
    - https://github.com/rizkyian78/e-ticket.git 

  destinations:
    - namespace: e-ticket
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
