apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: e-ticket
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:password@postgres:5432/ipg
  AMQP_URL: amqp://guest:guest@rabbitmq:5672/
