apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: e-ticket-ingress
  namespace: e-ticket
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rizkyiann8nautomation.my.id
      secretName: e-ticket-tls
  rules:
    - host: rizkyiann8nautomation.my.id
      http:
        paths:
          # =========================
          # CHECKOUT APP (assets FIRST)
          # =========================

          # =========================
          # BACKOFFICE
          # =========================
          - path: /backoffice
            pathType: Prefix
            backend:
              service:
                name: backoffice-app
                port:
                  number: 80

          # =========================
          # APIs
          # =========================
          - path: /api/inquiry
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 3000

          - path: /api/payment
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 3000

          - path: /api/ticket
            pathType: Prefix
            backend:
              service:
                name: ticket-service
                port:
                  number: 8080

          - path: /api/ledger
            pathType: Prefix
            backend:
              service:
                name: ledger-service
                port:
                  number: 8000

          # =========================
          # DEMOSHOP (ROOT LAST)
          # =========================
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demoshop
                port:
                  number: 80

