apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditcard-worker
  namespace: e-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creditcard-worker
  template:
    metadata:
      labels:
        app: creditcard-worker
    spec:
      containers:
        - name: creditcard-worker
          image: rizkyian78/e-ticketing-creditcard-worker:10ced76ff2daf0e3c252cf88844e341bd109fb4
          envFrom:
            - secretRef:
                name: app-secrets
