apiVersion: apps/v1
kind: Deployment
metadata:
  name: qris-worker
  namespace: e-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qris-worker
  template:
    metadata:
      labels:
        app: qris-worker
    spec:  # remove if image is public
      containers:
        - name: qris-worker
          image: rizkyian78/e-ticketing-qris-worker:9f84bcf
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: WORKER_TYPE
              value: "qris"
