name: CI Pipeline (Tests + Coverage + SonarQube + Docker)

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

env:
  SONAR_PROJECT_KEY: rizkyian78_e-ticket
  IMAGE_PREFIX: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/e-ticketing

jobs:

# =========================
# PR PIPELINE
# =========================
  pr-tests:
    if: github.event_name == 'pull_request'
    name: PR - Full Test Suite
    runs-on: ubuntu-latest
    environment: e-ticket

    steps:
      - uses: actions/checkout@v4

# ---------- FRONTEND ----------
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Frontend Tests
        run: |
          cd demoshop
          yarn install
          yarn lint || true
          yarn test

# ---------- PAYMENT ----------
      - name: Payment Tests
        run: |
          cd payment-service
          yarn install
          yarn lint || true
          yarn test

# ---------- LEDGER ----------
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Ledger Tests
        run: |
          cd ledger-service
          pip install -r requirements.txt
          pip install pytest
          pytest

# ---------- TICKET (.NET) ----------
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Ticket Tests
        run: |
          cd ticket-service
          dotnet restore
          dotnet test

# =========================
# MERGE PIPELINE
# =========================
  merge-tests-coverage-sonar:
    if: github.event_name == 'push'
    name: Merge - Test + Coverage + Sonar + Docker Push
    runs-on: ubuntu-latest
    environment: e-ticket

    steps:
      - uses: actions/checkout@v4

# ---------- FRONTEND ----------
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - name: Frontend Coverage
      #   run: |
      #     cd demoshop
      #     yarn install
      #     yarn test --coverage

# ---------- PAYMENT ----------
      # - name: Payment Coverage
      #   run: |
      #     cd payment-service
      #     yarn install
      #     yarn test --coverage

# ---------- LEDGER ----------
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.11"
      # - name: Ledger Coverage
      #   run: |
      #     cd ledger-service
      #     pip install -r requirements.txt
      #     pip install pytest pytest-cov flake8
      #     flake8 . || true
      #     pytest --cov=. --cov-report=xml

# ---------- TICKET (.NET) ----------
      # - uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: "8.0.x"
      # - name: Ticket Coverage
      #   run: |
      #     cd ticket-service
      #     dotnet test --collect:"XPlat Code Coverage"
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v2
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=rizkyian78_e-ticket
      #       -Dsonar.organization=rizkyian78
      #       -Dsonar.sources=.
        

# =========================
# QUALITY GATE
# =========================
      # - name: SonarQube Quality Gate
      #   uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
      #   timeout-minutes: 5
      #   continue-on-error: true
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

# =========================
# DOCKER LOGIN
# =========================
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          # =========================
# BUILD & PUSH IMAGES
# =========================
      - name: Build & Push Frontend Image
        run: |
           docker build --build-arg VITE_API_TICKET_SERVICE_URL=https://rizkyiann8nautomation.my.id/ \
            --build-arg VITE_API_PAYMENT_SERVICE_URL=https://rizkyiann8nautomation.my.id/ \
            --build-arg VITE_API_KEY=sk_live_9f8a7b6c5d4e3f2a1 \
            -t $IMAGE_PREFIX-frontend:$IMAGE_TAG demoshop
            docker push $IMAGE_PREFIX-frontend:$IMAGE_TAG
      - name: Build & Push Frontend Checkout Image
        run: |
          docker build \
          --build-arg VITE_API_BASE_URL=https://rizkyiann8nautomation.my.id/ \
          -t $IMAGE_PREFIX-checkout-app:$IMAGE_TAG checkout-app
          docker push $IMAGE_PREFIX-checkout-app:$IMAGE_TAG
      - name: Build & Push Frontend Backoffice Image
        run: |
          docker build -t $IMAGE_PREFIX-backoffice-app:$IMAGE_TAG backoffice-app
          docker push $IMAGE_PREFIX-backoffice-app:$IMAGE_TAG         

      - name: Build & Push Payment Image
        run: |
          docker build -t $IMAGE_PREFIX-payment:$IMAGE_TAG payment-service
          docker push $IMAGE_PREFIX-payment:$IMAGE_TAG

      - name: Build & Push Ledger Image
        run: |
          docker build -t $IMAGE_PREFIX-ledger:$IMAGE_TAG ledger-service
          docker push $IMAGE_PREFIX-ledger:$IMAGE_TAG

      - name: Build & Push Ticket Image
        run: |
          docker build -t $IMAGE_PREFIX-ticket:$IMAGE_TAG ticket-service
          docker push $IMAGE_PREFIX-ticket:$IMAGE_TAG
      - name: Build & Push Creditcard Worker Image
        run: |

          docker build \
          -t $IMAGE_PREFIX-creditcard-worker:$IMAGE_TAG \
          --build-arg CMD_NAME=creditcard \
          payment-method-worker

          docker push $IMAGE_PREFIX-creditcard-worker:$IMAGE_TAG
      - name: Build & Push QRIS Worker Image
        run: |
          docker build \
          --build-arg CMD_NAME=qris \
          -t $IMAGE_PREFIX-qris-worker:$IMAGE_TAG \
          payment-method-worker

          docker push $IMAGE_PREFIX-qris-worker:$IMAGE_TAG
      - name: Build & Push Debitcard Worker Image
        run: |
          docker build \
          --build-arg CMD_NAME=debitcard \
          -t $IMAGE_PREFIX-debitcard-worker:$IMAGE_TAG \
          payment-method-worker

          docker push $IMAGE_PREFIX-debitcard-worker:$IMAGE_TAG

# =========================
# UPLOAD COVERAGE
# =========================
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: full-code-coverage
          path: |
            demoshop/coverage
            payment-service/coverage
            ledger-service/coverage.xml
            ticket-service/**/coverage.opencover.xml
